TWITTER_KEY: 'mlTSgvfg7yxWeNcWEOSXA'
TWITTER_SECRET: 'URtmmzUzkUkFcEJx30J2uKscmOXOUf3yq8oqhRmTqY'
OAUTH_TOKEN: '91753078-cPApodCpUbpomUo48tcodYgMQh4Z4fDAWAIHuh7EH'
OAUTH_TOKEN_SECRET: 'zZmpW5NLMUPlafxwOne4EjeoZxWMFfyU58jTchzA'