TWITTER_KEY: '3JMFWT7JrdjtCFEOG1CfA'
TWITTER_SECRET: 'bnbZDLJHzD1EZ2fSXIjxQJ4ANaZ6aFPgn5Kg7ZwZslI'
OAUTH_TOKEN: '1920482970-9WwYPpYa2EsKRs90ymfU3Yg8H17jLF4w3TSjtRx'
OAUTH_TOKEN_SECRET: 'epiIXesBsllmJ7gttwn2raxJkW14ELYW0wZyNiONei0'