TWITTER_KEY: 'FCxuKv4kVPpGibJGG1yuQ'
TWITTER_SECRET: 'TZvRTV60Qt21GzSLZ7G6m3EK5JbwfMey31RHCoV8n5Q'
OAUTH_TOKEN: '1243904089-lbBINKAqKgjV7N4O4pLyxpEcn4YIgXiyMGlQitu'
OAUTH_TOKEN_SECRET: 'IhASFVemWSXC9nucfStUGHtH4ZVxk0q4ZoQFnRzvJw'